### ISSUE TITLE
Access to the source code

### ISSUE THREAD

**Issue by samymdihi** [samylee/SamyleePoseApi-OpenLibrary#1]
Hello @samylee, thanks for your work. Is it possible to have access to the source code ?

**Comment by samylee** [comment]
@samymdihi 
hi, sorry for that, the source code is not intended to be public at present, but c++ library is totally free to use.

**Comment by samymdihi** [comment]
Hey @samylee, which pose detection model did you use in your code ? Is it fastpose-duc from https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md ?

**Comment by samylee** [comment]
@samymdihi hi, just fastpose without duc.

**Comment by samymdihi** [comment]
Did you try with fastpose duc ? If yes what is the performance in terms of duration ?

**Comment by samylee** [comment]
@samymdihi Em...I haven't tried that, seems to be 5-10 ms slower?

**Comment by samymdihi** [comment]
Oh yeah I see. I am now trying to improve the performance of the algorithm. I reached 36ms per image with 20 people on each image. If you're interested we can talk in private. You can find my email in my profile page. It is pretty hard to improve the performance without having access to the source. I am planing to also add yolo to it to make it excatly look like Alphapose. I would be very grateful if you would agree to share the code.

**Comment by samylee** [comment]
Oh, sorry for not sharing the code due to some reasons that i can't tell, but i will share it in the future, please kindly wait.

**Comment by samymdihi** [comment]
Alright no problem, thanks

**Comment by samymdihi** [comment]
Hi @samylee, is it possible to get the confidence score for each joint with your algorithm ?

**Comment by samylee** [comment]
@samymdihi Yes, sounds wonderful advice, i may update library next week.
